default_root_dir: ???  # add this in local.yaml

dataset: 
    path: ???  # add this in local.yaml

seed: 0

training:
    batch_size: 2056
    num_workers: 30
    optim:
        lr: 5e-3
        max_lr: 5e-3
        weight_decay: 1e-5

    max_steps: 200000

logging:
    log_val_medias_every_n_epochs: 10
    log_train_medias_every_n_epochs: 10

domain_modules:
    attribute:
        nullify_rotation: false
    visual:
        color_blind: false

global_workspace:
    bayesian_gw: false

    domain_proportions: 
        -   domains: ["v"]
            proportion: 1.0
        -   domains: ["attr"]
            proportion: 1.0
        -   domains: ["v", "attr"]
            proportion: 1.0

